"""
ReportTemplateRegistry — manages HTML templates for clinical reports.
"""

from __future__ import annotations

from typing import Optional

from src.backend.reporting.models import ClinicalReport


class ReportTemplateRegistry:
    """Manages report rendering templates."""

    def __init__(self):
        self._templates: dict[str, str] = {
            "default": self._default_html_template,
        }

    def get_template(self, name: str = "default") -> str:
        return self._templates.get(name, self._default_html_template)

    def render_html(self, report: ClinicalReport, template_name: str = "default") -> str:
        """Render a report to HTML."""
        template = self.get_template(template_name)
        return self._apply_template(template, report)

    def _apply_template(self, template: str, report: ClinicalReport) -> str:
        """Apply report data to an HTML template."""
        rows = ""
        for variant in report.variants:
            rows += f"<tr><td>{variant.get('gene', '')}</td><td>{variant.get('hgvs', '')}</td></tr>\n"

        evidence_rows = ""
        for ev in report.evidence_summary:
            evidence_rows += (
                f"<tr><td>{ev.get('drug_name', '')}</td>"
                f"<td>{ev.get('evidence_direction', '')}</td>"
                f"<td>{ev.get('evidence_level', '')}</td></tr>\n"
            )

        ranking_rows = ""
        for drug in report.drug_ranking:
            ranking_rows += (
                f"<tr><td>{drug.get('rank', '')}</td>"
                f"<td>{drug.get('drug_name', '')}</td>"
                f"<td>{drug.get('total_score', 0)}</td></tr>\n"
            )

        return template.format(
            report_id=report.metadata.report_id,
            generated_at=report.metadata.generated_at,
            status=report.metadata.status,
            version=report.metadata.version,
            variant_rows=rows,
            evidence_rows=evidence_rows,
            ranking_rows=ranking_rows,
            reasoning_summary=(
                report.clinical_reasoning.get("summary", "")
                if report.clinical_reasoning else ""
            ),
            limitations="<br>".join(
                f"<li>{l}</li>" for l in report.limitations
            ) if report.limitations else "<li>None documented</li>",
            citations="<br>".join(
                f"[{c.get('pmid', '')}] {c.get('citation', '')[:100]}"
                for c in report.citations
            ) if report.citations else "None",
        )

    @property
    def _default_html_template(self) -> str:
        return """<!DOCTYPE html>
<html>
<head><title>Clinical Report {report_id}</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 20px; }}
.header {{ border-bottom: 2px solid #333; padding-bottom: 10px; }}
.section {{ margin: 20px 0; }}
table {{ width: 100%; border-collapse: collapse; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
th {{ background-color: #f2f2f2; }}
.footer {{ margin-top: 30px; font-size: 0.8em; color: #666; }}
.safety {{ background: #fff3cd; border: 1px solid #ffc107; padding: 10px; margin: 10px 0; }}
</style></head>
<body>
<div class="header">
<h1>Clinical Genomics Report</h1>
<p>Report ID: {report_id}</p>
<p>Generated: {generated_at}</p>
<p>Status: {status} | Version: {version}</p>
</div>

<div class="section">
<h2>Variants</h2>
<table><tr><th>Gene</th><th>Variant</th></tr>{variant_rows}</table>
</div>

<div class="section">
<h2>Evidence Summary</h2>
<table><tr><th>Drug</th><th>Direction</th><th>Level</th></tr>{evidence_rows}</table>
</div>

<div class="section">
<h2>Drug Rankings</h2>
<table><tr><th>Rank</th><th>Drug</th><th>Score</th></tr>{ranking_rows}</table>
</div>

<div class="section">
<h2>Clinical Reasoning</h2>
<p>{reasoning_summary}</p>
</div>

<div class="section">
<h2>Limitations</h2>
<ul>{limitations}</ul>
</div>

<div class="section">
<h2>Citations</h2>
<p>{citations}</p>
</div>

<div class="safety">
<strong>IMPORTANT:</strong> This report is for research and evidence organization purposes only.
It is NOT a clinical decision support system and must not be used for diagnosis or treatment decisions.
</div>

<div class="footer">
<p>Generated by AI-Kill-Cancer v0.8.0 | Git commit: pending</p>
</div>
</body></html>"""
